import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-50 text-gray-800 p-8 flex flex-col items-center">
      <div className="max-w-3xl w-full bg-white rounded-xl shadow-md p-8">
        <h1 className="text-3xl font-bold mb-4 text-center text-blue-700">
          Terms of Use
        </h1>

        <p className="mb-4">
          DocSoloScheduler is a simple online scheduling tool designed for solo
          providers such as chiropractors, massage therapists, physical therapists, or
          other single-location practices. It is provided by DocSolo Systems
          ("we", "us") for general professional use.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">1. Use at Your Own Risk</h2>
        <p className="mb-4">
          This software is offered <strong>as-is</strong> without any warranty
          or guarantee of uptime, data retention, or uninterrupted service. By
          using DocSoloScheduler, you accept full responsibility for how you
          use it and agree that we are not liable for any loss of income, data,
          or business disruption caused by downtime, bugs, or outages.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">2. Intended Users</h2>
        <p className="mb-4">
          DocSoloScheduler is intended for individual providers or small
          single-location practices. It is not designed for multi-location or
          multi-user enterprise use. Each provider account is for one user only.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">3. Data and Privacy</h2>
        <p className="mb-4">
          The system stores minimal data necessary to manage appointments
          (patient names, emails, phone numbers, and appointment times). No
          medical records or clinical information should be entered or stored.
          We do not sell, share, or use your data for marketing purposes.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">4. Email Use</h2>
        <p className="mb-4">
          All communications are sent via email only. By using this software,
          you agree to send and receive appointment-related emails generated by
          the system. Text messaging is not included.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">5. Termination</h2>
        <p className="mb-4">
          We may modify or discontinue DocSoloScheduler at any time without
          notice. You may stop using it at any time. There are no usage fees or
          contracts unless otherwise stated in writing.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">
          6. Acceptance of Terms
        </h2>
        <p className="mb-4">
          By creating an account or continuing to use DocSoloScheduler, you
          agree to these Terms of Use. If you do not agree, please discontinue
          use of the service.
        </p>

        <div className="flex justify-center mt-8">
          <Link to="/">
            <Button className="bg-blue-600 hover:bg-blue-700 text-white px-6">
              ← Back to DocSoloScheduler
            </Button>
          </Link>
        </div>

        <p className="text-center text-gray-500 text-sm mt-8">
          © {new Date().getFullYear()} DocSolo Systems · All rights reserved.
        </p>
      </div>
    </main>
  );
}
