name: Send Appointment Reminders

on:
  schedule:
    - cron: "0 * * * *"   # ⏰ runs at the top of every hour (UTC)
  workflow_dispatch:       # allows manual run from GitHub UI

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl --fail -s -X POST "https://pxwyzxwdqiwzpnbiupmd.functions.supabase.co/send-reminders" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
